task_DEV-3
DmitryZapryvaryn/TAT_2018 pull request #3
Opened 2018-03-06 19:05 UTC by DmitryZapryvaryn

2018-03-07 18:43 UTC, IgorKheidorov requested changes

2018-03-07 18:43 UTC, IgorKheidorov commented on Task_03/NumberBaseConverter.cs
> +        /// <exception cref="ArgumentException">Source number must be positive</exception>
Not changed number, number is the same, only the presentation changed

2018-03-07 18:43 UTC, IgorKheidorov commented on Task_03/NumberBaseConverter.cs
> +                remainder = (int)(sourceNumber % newBase);
can be simplified in one line

2018-03-08 18:34 UTC, AlexanderSoroka approved these changes
Approved due to deadline

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +    /// Provide a method for converts number's base
Not accurate class description

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +                    resultNumber.Insert(0, (char)(remainder + 55));
why +55?

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +            return UInt32.TryParse(stringBase, out result) && (result <= 20 && result >= 2);
single responsibility violation, wrong error-handling approach

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +                bool isDecimalNumber = UInt32.TryParse(args[0], out inputNumber);
wrong error-handling approach

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +        //If base of new number > 10 we need to use char A,B,C... in number.
useless comments, code must be self-descriptive

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +        private const byte AsciiStartChar = 55;
not obvious constant name

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +            if(sourceNumber < 0)
codestyle violation

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +            while(sourceNumber > 0)
too long method

2018-03-08 18:34 UTC, AlexanderSoroka commented on Task_03/NumberBaseConverter.cs
> +        /// <param name="newBase">New numeric system.</param>
Inaccurate param description

2018-03-12 02:59 UTC, merged